# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2021, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
# Translators:
# Arihiro TAKASE, 2017
# Osamu NAKAMURA, 2017
# tomo, 2020
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.9\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-01-07 05:06+0000\n"
"PO-Revision-Date: 2017-02-16 17:36+0000\n"
"Last-Translator: tomo, 2020\n"
"Language-Team: Japanese (https://www.transifex.com/python-doc/teams/5390/"
"ja/)\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ../../c-api/long.rst:6
msgid "Integer Objects"
msgstr "整数型オブジェクト (integer object)"

#: ../../c-api/long.rst:11
msgid ""
"All integers are implemented as \"long\" integer objects of arbitrary size."
msgstr "すべての整数は任意の長さをもつ \"long\" 整数として実装されます。"

#: ../../c-api/long.rst:13
msgid ""
"On error, most ``PyLong_As*`` APIs return ``(return type)-1`` which cannot "
"be distinguished from a number.  Use :c:func:`PyErr_Occurred` to "
"disambiguate."
msgstr ""
"エラーが起きると、ほとんどの ``PyLong_As*`` API は ``(return type)-1`` を返し"
"ますが、これは数値と見分けが付きません。\n"
"見分けを付けるためには :c:func:`PyErr_Occurred` を使ってください。"

#: ../../c-api/long.rst:18
msgid "This subtype of :c:type:`PyObject` represents a Python integer object."
msgstr "この :c:type:`PyObject` のサブタイプは整数型を表現します。"

#: ../../c-api/long.rst:23
msgid ""
"This instance of :c:type:`PyTypeObject` represents the Python integer type. "
"This is the same object as :class:`int` in the Python layer."
msgstr ""
"この :c:type:`PyTypeObject` のインスタンスは Python 整数型を表現します。これ"
"は Python レイヤにおける :class:`int` と同じオブジェクトです。"

#: ../../c-api/long.rst:29
msgid ""
"Return true if its argument is a :c:type:`PyLongObject` or a subtype of :c:"
"type:`PyLongObject`.  This function always succeeds."
msgstr ""
"引数が :c:type:`PyLongObject` か :c:type:`PyLongObject` のサブタイプであると"
"きに真を返します。この関数は常に成功します。"

#: ../../c-api/long.rst:35
msgid ""
"Return true if its argument is a :c:type:`PyLongObject`, but not a subtype "
"of :c:type:`PyLongObject`.  This function always succeeds."
msgstr ""
"引数が :c:type:`PyLongObject` であるが :c:type:`PyLongObject` のサブタイプで"
"ないときに真を返します。この関数は常に成功します。"

#: ../../c-api/long.rst:41
msgid ""
"Return a new :c:type:`PyLongObject` object from *v*, or ``NULL`` on failure."
msgstr ""
"*v* から新たな :c:type:`PyLongObject` オブジェクトを生成して返します。失敗の"
"ときには ``NULL`` を返します。"

#: ../../c-api/long.rst:43
msgid ""
"The current implementation keeps an array of integer objects for all "
"integers between ``-5`` and ``256``, when you create an int in that range "
"you actually just get back a reference to the existing object."
msgstr ""
"現在の実装では、``-5`` から ``256`` までの全ての整数に対する整数オブジェクト"
"の配列を保持するようにしており、この範囲の数を生成すると、実際には既存のオブ"
"ジェクトに対する参照が返るようになっています。"

#: ../../c-api/long.rst:50
msgid ""
"Return a new :c:type:`PyLongObject` object from a C :c:type:`unsigned long`, "
"or ``NULL`` on failure."
msgstr ""
"Cの :c:type:`unsigned long` から新たな :c:type:`PyLongObject` オブジェクトを"
"生成して返します。失敗した際には ``NULL`` を返します。"

#: ../../c-api/long.rst:56
msgid ""
"Return a new :c:type:`PyLongObject` object from a C :c:type:`Py_ssize_t`, or "
"``NULL`` on failure."
msgstr ""
"C の :c:type:`Py_ssize_t` 型から新たな :c:type:`PyLongObject` オブジェクトを"
"生成して返します。 失敗のときには ``NULL`` を返します。"

#: ../../c-api/long.rst:62
msgid ""
"Return a new :c:type:`PyLongObject` object from a C :c:type:`size_t`, or "
"``NULL`` on failure."
msgstr ""
"C の :c:type:`size_t` 型から新たな :c:type:`PyLongObject` オブジェクトを生成"
"して返します。 失敗のときには ``NULL`` を返します。"

#: ../../c-api/long.rst:68
msgid ""
"Return a new :c:type:`PyLongObject` object from a C :c:type:`long long`, or "
"``NULL`` on failure."
msgstr ""
"C の :c:type:`long long` 型から新たな :c:type:`PyLongObject` オブジェクトを生"
"成して返します。失敗のときには ``NULL`` を返します。"

#: ../../c-api/long.rst:74
msgid ""
"Return a new :c:type:`PyLongObject` object from a C :c:type:`unsigned long "
"long`, or ``NULL`` on failure."
msgstr ""
"C の :c:type:`unsigned long long` 型から新たな :c:type:`PyLongObject` オブ"
"ジェクトを生成して返します。失敗のときには ``NULL`` を返します。"

#: ../../c-api/long.rst:80
msgid ""
"Return a new :c:type:`PyLongObject` object from the integer part of *v*, or "
"``NULL`` on failure."
msgstr ""
"*v* の整数部から新たな :c:type:`PyLongObject` オブジェクトを生成して返しま"
"す。失敗のときには ``NULL`` を返します。"

#: ../../c-api/long.rst:86
msgid ""
"Return a new :c:type:`PyLongObject` based on the string value in *str*, "
"which is interpreted according to the radix in *base*.  If *pend* is non-"
"``NULL``, *\\*pend* will point to the first character in *str* which follows "
"the representation of the number.  If *base* is ``0``, *str* is interpreted "
"using the :ref:`integers` definition; in this case, leading zeros in a non-"
"zero decimal number raises a :exc:`ValueError`. If *base* is not ``0``, it "
"must be between ``2`` and ``36``, inclusive.  Leading spaces and single "
"underscores after a base specifier and between digits are ignored.  If there "
"are no digits, :exc:`ValueError` will be raised."
msgstr ""
"*str* の文字列値に基づいて、新たな :c:type:`PyLongObject` を返します。\n"
"このとき *base* を基数として文字列を解釈します。\n"
"*pend* が ``NULL`` でない場合は、 *\\*pend* は *str* 中で数が表現されている部"
"分以降の先頭文字のアドレスを指しています。\n"
"*base* が ``0`` の場合は、 *str* は :ref:`integers` の定義を使って解釈されま"
"す; この場合では、先頭に 0 がある 0 でない十進数は :exc:`ValueError` を送出し"
"ます。\n"
"*base* が ``0`` でなければ、 *base* は ``2`` 以上 ``36`` 以下の数でなければな"
"りません。\n"
"先頭の空白、基数の指定の後や数字の間にある単一のアンダースコアは無視されま"
"す。\n"
"数字が全くない場合、 :exc:`ValueError` が送出されます。"

#: ../../c-api/long.rst:99
msgid "Convert a sequence of Unicode digits to a Python integer value."
msgstr ""

#: ../../c-api/long.rst:103
msgid ""
"Part of the old-style :c:type:`Py_UNICODE` API; please migrate to using :c:"
"func:`PyLong_FromUnicodeObject`."
msgstr ""
"古いスタイルの :c:type:`Py_UNICODE` APIの一部です; :c:func:"
"`PyLong_FromUnicodeObject` を使用するように移行してください。"

#: ../../c-api/long.rst:108
msgid ""
"Convert a sequence of Unicode digits in the string *u* to a Python integer "
"value."
msgstr ""

#: ../../c-api/long.rst:116
msgid ""
"Create a Python integer from the pointer *p*. The pointer value can be "
"retrieved from the resulting value using :c:func:`PyLong_AsVoidPtr`."
msgstr ""
"ポインタ *p* から Python 整数値を生成します。ポインタの値は :c:func:"
"`PyLong_AsVoidPtr` を適用した結果から取得されます。"

#: ../../c-api/long.rst:127 ../../c-api/long.rst:146
msgid ""
"Return a C :c:type:`long` representation of *obj*.  If *obj* is not an "
"instance of :c:type:`PyLongObject`, first call its :meth:`__index__` or :"
"meth:`__int__` method (if present) to convert it to a :c:type:`PyLongObject`."
msgstr ""
"*obj* が表す、Cの :c:type:`long` 表現を返します。もし *obj* が :c:type:"
"`PyLongObject` のインスタンスでなければ、まず、その :meth:`__index__` メソッ"
"ドあるいは :meth:`__int__` メソッドを (もしあれば) 呼び出して、オブジェクト"
"を :c:type:`PyLongObject` に変換します。"

#: ../../c-api/long.rst:132
msgid ""
"Raise :exc:`OverflowError` if the value of *obj* is out of range for a :c:"
"type:`long`."
msgstr ""
"もし *obj* の値が :c:type:`long` の範囲外であれば、 :exc:`OverflowError` を送"
"出します。"

#: ../../c-api/long.rst:135 ../../c-api/long.rst:156 ../../c-api/long.rst:178
#: ../../c-api/long.rst:199 ../../c-api/long.rst:222
msgid "Returns ``-1`` on error.  Use :c:func:`PyErr_Occurred` to disambiguate."
msgstr ""
"エラーが起きたときに ``-1`` を返します。\n"
"見分けを付けるためには  :c:func:`PyErr_Occurred` を使ってください。"

#: ../../c-api/long.rst:137 ../../c-api/long.rst:158 ../../c-api/long.rst:180
#: ../../c-api/long.rst:203 ../../c-api/long.rst:288 ../../c-api/long.rst:308
msgid "Use :meth:`__index__` if available."
msgstr "可能であれば :meth:`__index__` を使うようになりました。"

#: ../../c-api/long.rst:140 ../../c-api/long.rst:161 ../../c-api/long.rst:183
#: ../../c-api/long.rst:206 ../../c-api/long.rst:291 ../../c-api/long.rst:311
msgid "Using :meth:`__int__` is deprecated."
msgstr ":meth:`__int__` の使用は非推奨です。"

#: ../../c-api/long.rst:151
msgid ""
"If the value of *obj* is greater than :const:`LONG_MAX` or less than :const:"
"`LONG_MIN`, set *\\*overflow* to ``1`` or ``-1``, respectively, and return "
"``-1``; otherwise, set *\\*overflow* to ``0``.  If any other exception "
"occurs set *\\*overflow* to ``0`` and return ``-1`` as usual."
msgstr ""
"もし、 *obj* の値が :const:`LONG_MAX` より大きいか、 :const:`LONG_MIN` より小"
"さければ、 *\\*overflow* は、それぞれ ``1`` か ``-1`` に設定され、 ``-1`` を"
"返します; さもなければ  *\\*overflow* は ``0`` に設定されます。もし、ほかの例"
"外が発生した場合は *\\*overflow* が ``0`` に設定され ``-1`` を返します。"

#: ../../c-api/long.rst:170 ../../c-api/long.rst:189
msgid ""
"Return a C :c:type:`long long` representation of *obj*.  If *obj* is not an "
"instance of :c:type:`PyLongObject`, first call its :meth:`__index__` or :"
"meth:`__int__` method (if present) to convert it to a :c:type:`PyLongObject`."
msgstr ""
"*obj* が表す、Cの :c:type:`long long` 表現を返します。\n"
"もし *obj* が :c:type:`PyLongObject` のインスタンスでなければ、まず、その :"
"meth:`__index__` メソッドあるいは :meth:`__int__` メソッドを (もしあれば) 呼"
"び出して、オブジェクトを :c:type:`PyLongObject` に変換します。"

#: ../../c-api/long.rst:175
msgid ""
"Raise :exc:`OverflowError` if the value of *obj* is out of range for a :c:"
"type:`long long`."
msgstr ""
"もし *obj* の値が :c:type:`long long` の範囲外であれば、 :exc:"
"`OverflowError` を送出します。"

#: ../../c-api/long.rst:194
msgid ""
"If the value of *obj* is greater than :const:`LLONG_MAX` or less than :const:"
"`LLONG_MIN`, set *\\*overflow* to ``1`` or ``-1``, respectively, and return "
"``-1``; otherwise, set *\\*overflow* to ``0``.  If any other exception "
"occurs set *\\*overflow* to ``0`` and return ``-1`` as usual."
msgstr ""
"もし、 *obj* の値が :const:`LLONG_MAX` より大きいか、 :const:`LLONG_MIN` より"
"小さければ、 *\\*overflow* は、それぞれ ``1`` か ``-1`` に設定され、 ``-1`` "
"を返します; さもなければ  *\\*overflow* は ``0`` に設定されます。もし、ほかの"
"例外が発生した場合は *\\*overflow* が ``0`` に設定され ``-1`` を返します。"

#: ../../c-api/long.rst:216
msgid ""
"Return a C :c:type:`Py_ssize_t` representation of *pylong*.  *pylong* must "
"be an instance of :c:type:`PyLongObject`."
msgstr ""
"*pylong* を表す C の :c:type:`Py_ssize_t` を返します。 *pylong* は :c:type:"
"`PyLongObject` のインスタンスでなければなりません。"

#: ../../c-api/long.rst:219
msgid ""
"Raise :exc:`OverflowError` if the value of *pylong* is out of range for a :c:"
"type:`Py_ssize_t`."
msgstr ""
"もし *pylong* の値が :c:type:`Py_ssize_t` の範囲外であれば、 :exc:"
"`OverflowError` を送出します。"

#: ../../c-api/long.rst:231
msgid ""
"Return a C :c:type:`unsigned long` representation of *pylong*.  *pylong* "
"must be an instance of :c:type:`PyLongObject`."
msgstr ""
"*pylong* を表す C の :c:type:`unsigned long` を返します。 *pylong* は :c:"
"type:`PyLongObject` のインスタンスでなければなりません。"

#: ../../c-api/long.rst:234
msgid ""
"Raise :exc:`OverflowError` if the value of *pylong* is out of range for a :c:"
"type:`unsigned long`."
msgstr ""
"もし *pylong* の値が :c:type:`unsigned long` の範囲外であれば、 :exc:"
"`OverflowError` を送出します。"

#: ../../c-api/long.rst:237
msgid ""
"Returns ``(unsigned long)-1`` on error. Use :c:func:`PyErr_Occurred` to "
"disambiguate."
msgstr ""
"エラーが起きたときに ``(unsigned long)-1`` を返します。\n"
"見分けを付けるためには  :c:func:`PyErr_Occurred` を使ってください。"

#: ../../c-api/long.rst:247
msgid ""
"Return a C :c:type:`size_t` representation of *pylong*.  *pylong* must be an "
"instance of :c:type:`PyLongObject`."
msgstr ""
"*pylong* を表す C の :c:type:`size_t` を返します。 *pylong* は :c:type:"
"`PyLongObject` のインスタンスでなければなりません。"

#: ../../c-api/long.rst:250
msgid ""
"Raise :exc:`OverflowError` if the value of *pylong* is out of range for a :c:"
"type:`size_t`."
msgstr ""
"もし *pylong* の値が :c:type:`size_t` の範囲外であれば、 :exc:"
"`OverflowError` を送出します。"

#: ../../c-api/long.rst:253
msgid ""
"Returns ``(size_t)-1`` on error. Use :c:func:`PyErr_Occurred` to "
"disambiguate."
msgstr ""
"エラーが起きたときに ``(size_t)-1`` を返します。\n"
"見分けを付けるためには  :c:func:`PyErr_Occurred` を使ってください。"

#: ../../c-api/long.rst:262
msgid ""
"Return a C :c:type:`unsigned long long` representation of *pylong*.  "
"*pylong* must be an instance of :c:type:`PyLongObject`."
msgstr ""
"*pylong* を表す C の :c:type:`unsigned long long` を返します。 *pylong* は :"
"c:type:`PyLongObject` のインスタンスでなければなりません。"

#: ../../c-api/long.rst:265
msgid ""
"Raise :exc:`OverflowError` if the value of *pylong* is out of range for an :"
"c:type:`unsigned long long`."
msgstr ""
"もし *pylong* の値が :c:type:`unsigned long long` の範囲外であれば、 :exc:"
"`OverflowError` を送出します。"

#: ../../c-api/long.rst:268
msgid ""
"Returns ``(unsigned long long)-1`` on error. Use :c:func:`PyErr_Occurred` to "
"disambiguate."
msgstr ""
"エラーが起きたときに ``(unsigned long long)-1`` を返します。\n"
"見分けを付けるためには  :c:func:`PyErr_Occurred` を使ってください。"

#: ../../c-api/long.rst:271
msgid ""
"A negative *pylong* now raises :exc:`OverflowError`, not :exc:`TypeError`."
msgstr ""
"負 *pylong* を指定した際に :exc:`TypeError` ではなく、 :exc:`OverflowError` "
"を送出するようになりました。"

#: ../../c-api/long.rst:277
msgid ""
"Return a C :c:type:`unsigned long` representation of *obj*.  If *obj* is not "
"an instance of :c:type:`PyLongObject`, first call its :meth:`__index__` or :"
"meth:`__int__` method (if present) to convert it to a :c:type:`PyLongObject`."
msgstr ""
"*obj* が表す、Cの :c:type:`unsigned long` 表現を返します。\n"
"もし *obj* が :c:type:`PyLongObject` のインスタンスでなければ、まず、その :"
"meth:`__index__` メソッドあるいは :meth:`__int__` メソッドを (もしあれば) 呼"
"び出して、オブジェクトを :c:type:`PyLongObject` に変換します。"

#: ../../c-api/long.rst:282
msgid ""
"If the value of *obj* is out of range for an :c:type:`unsigned long`, return "
"the reduction of that value modulo ``ULONG_MAX + 1``."
msgstr ""
"*obj* の値が :c:type:`unsigned long` の範囲から外れていた場合は、 "
"``ULONG_MAX + 1`` を法とした剰余を返します。"

#: ../../c-api/long.rst:285
msgid ""
"Returns ``(unsigned long)-1`` on error.  Use :c:func:`PyErr_Occurred` to "
"disambiguate."
msgstr ""
"エラーが起きたときに ``(unsigned long)-1`` を返します。\n"
"見分けを付けるためには  :c:func:`PyErr_Occurred` を使ってください。"

#: ../../c-api/long.rst:297
msgid ""
"Return a C :c:type:`unsigned long long` representation of *obj*.  If *obj* "
"is not an instance of :c:type:`PyLongObject`, first call its :meth:"
"`__index__` or :meth:`__int__` method (if present) to convert it to a :c:"
"type:`PyLongObject`."
msgstr ""
"*obj* が表す、Cの :c:type:`unsigned long long` 表現を返します。\n"
"もし *obj* が :c:type:`PyLongObject` のインスタンスでなければ、まず、その :"
"meth:`__index__` メソッドあるいは :meth:`__int__` メソッドを (もしあれば) 呼"
"び出して、オブジェクトを :c:type:`PyLongObject` に変換します。"

#: ../../c-api/long.rst:302
msgid ""
"If the value of *obj* is out of range for an :c:type:`unsigned long long`, "
"return the reduction of that value modulo ``ULLONG_MAX + 1``."
msgstr ""
"*obj* の値が :c:type:`unsigned long long` の範囲から外れていた場合は、 "
"``ULLONG_MAX + 1`` を法とした剰余を返します。"

#: ../../c-api/long.rst:305
msgid ""
"Returns ``(unsigned long long)-1`` on error.  Use :c:func:`PyErr_Occurred` "
"to disambiguate."
msgstr ""
"エラーが起きたときに ``(unsigned long long)-1`` を返します。\n"
"見分けを付けるためには  :c:func:`PyErr_Occurred` を使ってください。"

#: ../../c-api/long.rst:317
msgid ""
"Return a C :c:type:`double` representation of *pylong*.  *pylong* must be an "
"instance of :c:type:`PyLongObject`."
msgstr ""
"*pylong* を表す C の :c:type:`double` を返します。 *pylong* は :c:type:"
"`PyLongObject` のインスタンスでなければなりません。"

#: ../../c-api/long.rst:320
msgid ""
"Raise :exc:`OverflowError` if the value of *pylong* is out of range for a :c:"
"type:`double`."
msgstr ""
"もし *pylong* の値が :c:type:`double` の範囲外であれば、 :exc:"
"`OverflowError` を送出します。"

#: ../../c-api/long.rst:323
msgid ""
"Returns ``-1.0`` on error.  Use :c:func:`PyErr_Occurred` to disambiguate."
msgstr ""
"エラーが起きたときに ``-1.0`` を返します。\n"
"見分けを付けるためには  :c:func:`PyErr_Occurred` を使ってください。"

#: ../../c-api/long.rst:328
msgid ""
"Convert a Python integer *pylong* to a C :c:type:`void` pointer. If *pylong* "
"cannot be converted, an :exc:`OverflowError` will be raised.  This is only "
"assured to produce a usable :c:type:`void` pointer for values created with :"
"c:func:`PyLong_FromVoidPtr`."
msgstr ""
"Python の整数型を指す *pylong* を、 C の :c:type:`void` ポインタに変換しま"
"す。 *pylong* を変換できなければ、 :exc:`OverflowError` を送出します。この関"
"数は :c:func:`PyLong_FromVoidPtr` で値を生成するときに使うような :c:type:"
"`void` ポインタ型を生成できるだけです。"

#: ../../c-api/long.rst:333
msgid ""
"Returns ``NULL`` on error.  Use :c:func:`PyErr_Occurred` to disambiguate."
msgstr ""
"エラーが起きたときに ``NULL`` を返します。\n"
"見分けを付けるためには  :c:func:`PyErr_Occurred` を使ってください。"
