# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2021, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
# Translators:
# tomo, 2020
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.7\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-01-01 16:02+0000\n"
"PO-Revision-Date: 2019-09-01 03:38+0000\n"
"Last-Translator: tomo, 2020\n"
"Language-Team: Japanese (https://www.transifex.com/python-doc/teams/5390/"
"ja/)\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ../../c-api/long.rst:6
msgid "Integer Objects"
msgstr "整数型オブジェクト (integer object)"

#: ../../c-api/long.rst:11
msgid ""
"All integers are implemented as \"long\" integer objects of arbitrary size."
msgstr "すべての整数は任意の長さをもつ \"long\" 整数として実装されます。"

#: ../../c-api/long.rst:13
msgid ""
"On error, most ``PyLong_As*`` APIs return ``(return type)-1`` which cannot "
"be distinguished from a number.  Use :c:func:`PyErr_Occurred` to "
"disambiguate."
msgstr ""
"エラーが起きると、ほとんどの ``PyLong_As*`` API は ``(return type)-1`` を返し"
"ますが、これは数値と見分けが付きません。\n"
"見分けを付けるためには :c:func:`PyErr_Occurred` を使ってください。"

#: ../../c-api/long.rst:18
msgid "This subtype of :c:type:`PyObject` represents a Python integer object."
msgstr "この :c:type:`PyObject` のサブタイプは整数型を表現します。"

#: ../../c-api/long.rst:23
msgid ""
"This instance of :c:type:`PyTypeObject` represents the Python integer type. "
"This is the same object as :class:`int` in the Python layer."
msgstr ""
"この :c:type:`PyTypeObject` のインスタンスは Python 整数型を表現します。これ"
"は Python レイヤにおける :class:`int` と同じオブジェクトです。"

#: ../../c-api/long.rst:29
msgid ""
"Return true if its argument is a :c:type:`PyLongObject` or a subtype of :c:"
"type:`PyLongObject`."
msgstr ""
"引数が :c:type:`PyLongObject` か :c:type:`PyLongObject` のサブタイプのときに"
"真を返します。"

#: ../../c-api/long.rst:35
msgid ""
"Return true if its argument is a :c:type:`PyLongObject`, but not a subtype "
"of :c:type:`PyLongObject`."
msgstr ""
"引数が :c:type:`PyLongObject` 型で、かつ :c:type:`PyLongObject` 型のサブタイ"
"プでないときに真を返します。"

#: ../../c-api/long.rst:41
msgid ""
"Return a new :c:type:`PyLongObject` object from *v*, or ``NULL`` on failure."
msgstr ""
"*v* から新たな :c:type:`PyLongObject` オブジェクトを生成して返します。失敗の"
"ときには ``NULL`` を返します。"

#: ../../c-api/long.rst:43
msgid ""
"The current implementation keeps an array of integer objects for all "
"integers between ``-5`` and ``256``, when you create an int in that range "
"you actually just get back a reference to the existing object. So it should "
"be possible to change the value of ``1``.  I suspect the behaviour of Python "
"in this case is undefined. :-)"
msgstr ""
"現在の実装では、``-5`` から ``256`` までの全ての整数に対する整数オブジェクト"
"の配列を保持するようにしており、この範囲の数を生成すると、実際には既存のオブ"
"ジェクトに対する参照が返るようになっています。従って、``1`` の値を変えること"
"すら可能です。変えてしまった場合の Python の挙動は未定義です :-)"

#: ../../c-api/long.rst:52
msgid ""
"Return a new :c:type:`PyLongObject` object from a C :c:type:`unsigned long`, "
"or ``NULL`` on failure."
msgstr ""
"Cの :c:type:`unsigned long` から新たな :c:type:`PyLongObject` オブジェクトを"
"生成して返します。失敗した際には ``NULL`` を返します。"

#: ../../c-api/long.rst:58
msgid ""
"Return a new :c:type:`PyLongObject` object from a C :c:type:`Py_ssize_t`, or "
"``NULL`` on failure."
msgstr ""
"C の :c:type:`Py_ssize_t` 型から新たな :c:type:`PyLongObject` オブジェクトを"
"生成して返します。 失敗のときには ``NULL`` を返します。"

#: ../../c-api/long.rst:64
msgid ""
"Return a new :c:type:`PyLongObject` object from a C :c:type:`size_t`, or "
"``NULL`` on failure."
msgstr ""
"C の :c:type:`size_t` 型から新たな :c:type:`PyLongObject` オブジェクトを生成"
"して返します。 失敗のときには ``NULL`` を返します。"

#: ../../c-api/long.rst:70
msgid ""
"Return a new :c:type:`PyLongObject` object from a C :c:type:`long long`, or "
"``NULL`` on failure."
msgstr ""
"C の :c:type:`long long` 型から新たな :c:type:`PyLongObject` オブジェクトを生"
"成して返します。失敗のときには ``NULL`` を返します。"

#: ../../c-api/long.rst:76
msgid ""
"Return a new :c:type:`PyLongObject` object from a C :c:type:`unsigned long "
"long`, or ``NULL`` on failure."
msgstr ""
"C の :c:type:`unsigned long long` 型から新たな :c:type:`PyLongObject` オブ"
"ジェクトを生成して返します。失敗のときには ``NULL`` を返します。"

#: ../../c-api/long.rst:82
msgid ""
"Return a new :c:type:`PyLongObject` object from the integer part of *v*, or "
"``NULL`` on failure."
msgstr ""
"*v* の整数部から新たな :c:type:`PyLongObject` オブジェクトを生成して返しま"
"す。失敗のときには ``NULL`` を返します。"

#: ../../c-api/long.rst:88
msgid ""
"Return a new :c:type:`PyLongObject` based on the string value in *str*, "
"which is interpreted according to the radix in *base*.  If *pend* is non-"
"``NULL``, *\\*pend* will point to the first character in *str* which follows "
"the representation of the number.  If *base* is ``0``, *str* is interpreted "
"using the :ref:`integers` definition; in this case, leading zeros in a non-"
"zero decimal number raises a :exc:`ValueError`. If *base* is not ``0``, it "
"must be between ``2`` and ``36``, inclusive.  Leading spaces and single "
"underscores after a base specifier and between digits are ignored.  If there "
"are no digits, :exc:`ValueError` will be raised."
msgstr ""
"*str* の文字列値に基づいて、新たな :c:type:`PyLongObject` を返します。\n"
"このとき *base* を基数として文字列を解釈します。\n"
"*pend* が ``NULL`` でない場合は、 *\\*pend* は *str* 中で数が表現されている部"
"分以降の先頭文字のアドレスを指しています。\n"
"*base* が ``0`` の場合は、 *str* は :ref:`integers` の定義を使って解釈されま"
"す; この場合では、先頭に 0 がある 0 でない十進数は :exc:`ValueError` を送出し"
"ます。\n"
"*base* が ``0`` でなければ、 *base* は ``2`` 以上 ``36`` 以下の数でなければな"
"りません。\n"
"先頭の空白、基数の指定の後や数字の間にある単一のアンダースコアは無視されま"
"す。\n"
"数字が全くない場合、 :exc:`ValueError` が送出されます。"

#: ../../c-api/long.rst:101
msgid ""
"Convert a sequence of Unicode digits to a Python integer value.  The Unicode "
"string is first encoded to a byte string using :c:func:"
"`PyUnicode_EncodeDecimal` and then converted using :c:func:"
"`PyLong_FromString`."
msgstr ""
"Unicode 数値列を Python 整数値に変換します。Unicode 文字列はまず :c:func:"
"`PyUnicode_EncodeDecimal` を用いてバイト文字列にエンコードされ、次に :c:func:"
"`PyLong_FromString` を用いて変換されます。"

#: ../../c-api/long.rst:107
msgid ""
"Part of the old-style :c:type:`Py_UNICODE` API; please migrate to using :c:"
"func:`PyLong_FromUnicodeObject`."
msgstr ""
"古いスタイルの :c:type:`Py_UNICODE` APIの一部です; :c:func:"
"`PyLong_FromUnicodeObject` を使用するように移行してください。"

#: ../../c-api/long.rst:112
msgid ""
"Convert a sequence of Unicode digits in the string *u* to a Python integer "
"value.  The Unicode string is first encoded to a byte string using :c:func:"
"`PyUnicode_EncodeDecimal` and then converted using :c:func:"
"`PyLong_FromString`."
msgstr ""
"*u* 文字列中の Unicode 数値列を Python 整数値に変換します。Unicode 文字列はま"
"ず :c:func:`PyUnicode_EncodeDecimal` を用いてバイト文字列にエンコードされ、次"
"に :c:func:`PyLong_FromString` を用いて変換されます。"

#: ../../c-api/long.rst:122
msgid ""
"Create a Python integer from the pointer *p*. The pointer value can be "
"retrieved from the resulting value using :c:func:`PyLong_AsVoidPtr`."
msgstr ""
"ポインタ *p* から Python 整数値を生成します。ポインタの値は :c:func:"
"`PyLong_AsVoidPtr` を適用した結果から取得されます。"

#: ../../c-api/long.rst:133 ../../c-api/long.rst:145
msgid ""
"Return a C :c:type:`long` representation of *obj*.  If *obj* is not an "
"instance of :c:type:`PyLongObject`, first call its :meth:`__int__` method "
"(if present) to convert it to a :c:type:`PyLongObject`."
msgstr ""
"*obj* が表す、Cの :c:type:`long` 表現を返します。もし *obj* が :c:type:"
"`PyLongObject` のインスタンスでなければ、まず、その :meth:`__int__` メソッド"
"を (もしあれば) 呼び出して、オブジェクトを :c:type:`PyLongObject` に変換しま"
"す。"

#: ../../c-api/long.rst:137
msgid ""
"Raise :exc:`OverflowError` if the value of *obj* is out of range for a :c:"
"type:`long`."
msgstr ""
"もし *obj* の値が :c:type:`long` の範囲外であれば、 :exc:`OverflowError` を送"
"出します。"

#: ../../c-api/long.rst:140 ../../c-api/long.rst:154 ../../c-api/long.rst:169
#: ../../c-api/long.rst:183 ../../c-api/long.rst:200
msgid "Returns ``-1`` on error.  Use :c:func:`PyErr_Occurred` to disambiguate."
msgstr ""
"エラーが起きたときに ``-1`` を返します。\n"
"見分けを付けるためには  :c:func:`PyErr_Occurred` を使ってください。"

#: ../../c-api/long.rst:149
msgid ""
"If the value of *obj* is greater than :const:`LONG_MAX` or less than :const:"
"`LONG_MIN`, set *\\*overflow* to ``1`` or ``-1``, respectively, and return "
"``-1``; otherwise, set *\\*overflow* to ``0``.  If any other exception "
"occurs set *\\*overflow* to ``0`` and return ``-1`` as usual."
msgstr ""
"もし、 *obj* の値が :const:`LONG_MAX` より大きいか、 :const:`LONG_MIN` より小"
"さければ、 *\\*overflow* は、それぞれ ``1`` か ``-1`` に設定され、 ``-1`` を"
"返します; さもなければ  *\\*overflow* は ``0`` に設定されます。もし、ほかの例"
"外が発生した場合は *\\*overflow* が ``0`` に設定され ``-1`` を返します。"

#: ../../c-api/long.rst:162 ../../c-api/long.rst:174
msgid ""
"Return a C :c:type:`long long` representation of *obj*.  If *obj* is not an "
"instance of :c:type:`PyLongObject`, first call its :meth:`__int__` method "
"(if present) to convert it to a :c:type:`PyLongObject`."
msgstr ""
"*obj* が表す、Cの :c:type:`long long` 表現を返します。もし *obj* が :c:type:"
"`PyLongObject` のインスタンスでなければ、まず、その :meth:`__int__` メソッド"
"を (もしあれば) 呼び出して、オブジェクトを :c:type:`PyLongObject` に変換しま"
"す。"

#: ../../c-api/long.rst:166
msgid ""
"Raise :exc:`OverflowError` if the value of *obj* is out of range for a :c:"
"type:`long long`."
msgstr ""
"もし *obj* の値が :c:type:`long long` の範囲外であれば、 :exc:"
"`OverflowError` を送出します。"

#: ../../c-api/long.rst:178
msgid ""
"If the value of *obj* is greater than :const:`PY_LLONG_MAX` or less than :"
"const:`PY_LLONG_MIN`, set *\\*overflow* to ``1`` or ``-1``, respectively, "
"and return ``-1``; otherwise, set *\\*overflow* to ``0``.  If any other "
"exception occurs set *\\*overflow* to ``0`` and return ``-1`` as usual."
msgstr ""
"もし、 *obj* の値が :const:`PY_LLONG_MAX` より大きいか、 :const:"
"`PY_LLONG_MIN` より小さければ、 *\\*overflow* は、それぞれ ``1`` か ``-1`` に"
"設定され、 ``-1`` を返します; さもなければ  *\\*overflow* は ``0`` に設定され"
"ます。もし、ほかの例外が発生した場合は *\\*overflow* が ``0`` に設定され "
"``-1`` を返します。"

#: ../../c-api/long.rst:194
msgid ""
"Return a C :c:type:`Py_ssize_t` representation of *pylong*.  *pylong* must "
"be an instance of :c:type:`PyLongObject`."
msgstr ""
"*pylong* を表す C の :c:type:`Py_ssize_t` を返します。 *pylong* は :c:type:"
"`PyLongObject` のインスタンスでなければなりません。"

#: ../../c-api/long.rst:197
msgid ""
"Raise :exc:`OverflowError` if the value of *pylong* is out of range for a :c:"
"type:`Py_ssize_t`."
msgstr ""
"もし *pylong* の値が :c:type:`Py_ssize_t` の範囲外であれば、 :exc:"
"`OverflowError` を送出します。"

#: ../../c-api/long.rst:209
msgid ""
"Return a C :c:type:`unsigned long` representation of *pylong*.  *pylong* "
"must be an instance of :c:type:`PyLongObject`."
msgstr ""
"*pylong* を表す C の :c:type:`unsigned long` を返します。 *pylong* は :c:"
"type:`PyLongObject` のインスタンスでなければなりません。"

#: ../../c-api/long.rst:212
msgid ""
"Raise :exc:`OverflowError` if the value of *pylong* is out of range for a :c:"
"type:`unsigned long`."
msgstr ""
"もし *pylong* の値が :c:type:`unsigned long` の範囲外であれば、 :exc:"
"`OverflowError` を送出します。"

#: ../../c-api/long.rst:215
msgid ""
"Returns ``(unsigned long)-1`` on error. Use :c:func:`PyErr_Occurred` to "
"disambiguate."
msgstr ""
"エラーが起きたときに ``(unsigned long)-1`` を返します。\n"
"見分けを付けるためには  :c:func:`PyErr_Occurred` を使ってください。"

#: ../../c-api/long.rst:225
msgid ""
"Return a C :c:type:`size_t` representation of *pylong*.  *pylong* must be an "
"instance of :c:type:`PyLongObject`."
msgstr ""
"*pylong* を表す C の :c:type:`size_t` を返します。 *pylong* は :c:type:"
"`PyLongObject` のインスタンスでなければなりません。"

#: ../../c-api/long.rst:228
msgid ""
"Raise :exc:`OverflowError` if the value of *pylong* is out of range for a :c:"
"type:`size_t`."
msgstr ""
"もし *pylong* の値が :c:type:`size_t` の範囲外であれば、 :exc:"
"`OverflowError` を送出します。"

#: ../../c-api/long.rst:231
msgid ""
"Returns ``(size_t)-1`` on error. Use :c:func:`PyErr_Occurred` to "
"disambiguate."
msgstr ""
"エラーが起きたときに ``(size_t)-1`` を返します。\n"
"見分けを付けるためには  :c:func:`PyErr_Occurred` を使ってください。"

#: ../../c-api/long.rst:240
msgid ""
"Return a C :c:type:`unsigned long long` representation of *pylong*.  "
"*pylong* must be an instance of :c:type:`PyLongObject`."
msgstr ""
"*pylong* を表す C の :c:type:`unsigned long long` を返します。 *pylong* は :"
"c:type:`PyLongObject` のインスタンスでなければなりません。"

#: ../../c-api/long.rst:243
msgid ""
"Raise :exc:`OverflowError` if the value of *pylong* is out of range for an :"
"c:type:`unsigned long long`."
msgstr ""
"もし *pylong* の値が :c:type:`unsigned long long` の範囲外であれば、 :exc:"
"`OverflowError` を送出します。"

#: ../../c-api/long.rst:246
msgid ""
"Returns ``(unsigned long long)-1`` on error. Use :c:func:`PyErr_Occurred` to "
"disambiguate."
msgstr ""
"エラーが起きたときに ``(unsigned long long)-1`` を返します。\n"
"見分けを付けるためには  :c:func:`PyErr_Occurred` を使ってください。"

#: ../../c-api/long.rst:249
msgid ""
"A negative *pylong* now raises :exc:`OverflowError`, not :exc:`TypeError`."
msgstr ""
"負 *pylong* を指定した際に :exc:`TypeError` ではなく、 :exc:`OverflowError` "
"を送出するようになりました。"

#: ../../c-api/long.rst:255
msgid ""
"Return a C :c:type:`unsigned long` representation of *obj*.  If *obj* is not "
"an instance of :c:type:`PyLongObject`, first call its :meth:`__int__` method "
"(if present) to convert it to a :c:type:`PyLongObject`."
msgstr ""
"*obj* が表す、C の :c:type:`unsigned long` 表現を返します。もし *obj* が :c:"
"type:`PyLongObject` のインスタンスでなければ、まず、その :meth:`__int__` メ"
"ソッドを (もしあれば) 呼び出して、オブジェクトを :c:type:`PyLongObject` に変"
"換します。"

#: ../../c-api/long.rst:259
msgid ""
"If the value of *obj* is out of range for an :c:type:`unsigned long`, return "
"the reduction of that value modulo ``ULONG_MAX + 1``."
msgstr ""
"*obj* の値が :c:type:`unsigned long` の範囲から外れていた場合は、 "
"``ULONG_MAX + 1`` を法とした剰余を返します。"

#: ../../c-api/long.rst:262
msgid ""
"Returns ``(unsigned long)-1`` on error.  Use :c:func:`PyErr_Occurred` to "
"disambiguate."
msgstr ""
"エラーが起きたときに ``(unsigned long)-1`` を返します。\n"
"見分けを付けるためには  :c:func:`PyErr_Occurred` を使ってください。"

#: ../../c-api/long.rst:268
msgid ""
"Return a C :c:type:`unsigned long long` representation of *obj*.  If *obj* "
"is not an instance of :c:type:`PyLongObject`, first call its :meth:`__int__` "
"method (if present) to convert it to a :c:type:`PyLongObject`."
msgstr ""
"*obj* が表す、C の :c:type:`unsigned long long` 表現を返します。もし *obj* "
"が :c:type:`PyLongObject` のインスタンスでなければ、まず、その :meth:"
"`__int__` メソッドを (もしあれば) 呼び出して、オブジェクトを :c:type:"
"`PyLongObject` に変換します。"

#: ../../c-api/long.rst:272
msgid ""
"If the value of *obj* is out of range for an :c:type:`unsigned long long`, "
"return the reduction of that value modulo ``PY_ULLONG_MAX + 1``."
msgstr ""
"*obj* の値が :c:type:`unsigned long long` の範囲から外れていた場合は、 "
"``PY_ULLONG_MAX + 1`` を法とした剰余を返します。"

#: ../../c-api/long.rst:275
msgid ""
"Returns ``(unsigned long long)-1`` on error.  Use :c:func:`PyErr_Occurred` "
"to disambiguate."
msgstr ""
"エラーが起きたときに ``(unsigned long long)-1`` を返します。\n"
"見分けを付けるためには  :c:func:`PyErr_Occurred` を使ってください。"

#: ../../c-api/long.rst:281
msgid ""
"Return a C :c:type:`double` representation of *pylong*.  *pylong* must be an "
"instance of :c:type:`PyLongObject`."
msgstr ""
"*pylong* を表す C の :c:type:`double` を返します。 *pylong* は :c:type:"
"`PyLongObject` のインスタンスでなければなりません。"

#: ../../c-api/long.rst:284
msgid ""
"Raise :exc:`OverflowError` if the value of *pylong* is out of range for a :c:"
"type:`double`."
msgstr ""
"もし *pylong* の値が :c:type:`double` の範囲外であれば、 :exc:"
"`OverflowError` を送出します。"

#: ../../c-api/long.rst:287
msgid ""
"Returns ``-1.0`` on error.  Use :c:func:`PyErr_Occurred` to disambiguate."
msgstr ""
"エラーが起きたときに ``-1.0`` を返します。\n"
"見分けを付けるためには  :c:func:`PyErr_Occurred` を使ってください。"

#: ../../c-api/long.rst:292
msgid ""
"Convert a Python integer *pylong* to a C :c:type:`void` pointer. If *pylong* "
"cannot be converted, an :exc:`OverflowError` will be raised.  This is only "
"assured to produce a usable :c:type:`void` pointer for values created with :"
"c:func:`PyLong_FromVoidPtr`."
msgstr ""
"Python の整数型を指す *pylong* を、 C の :c:type:`void` ポインタに変換しま"
"す。 *pylong* を変換できなければ、 :exc:`OverflowError` を送出します。この関"
"数は :c:func:`PyLong_FromVoidPtr` で値を生成するときに使うような :c:type:"
"`void` ポインタ型を生成できるだけです。"

#: ../../c-api/long.rst:297
msgid ""
"Returns ``NULL`` on error.  Use :c:func:`PyErr_Occurred` to disambiguate."
msgstr ""
"エラーが起きたときに ``NULL`` を返します。\n"
"見分けを付けるためには  :c:func:`PyErr_Occurred` を使ってください。"
